INSERT INTO roles (id,name) VALUES (3,'ROLE_ADMIN');
INSERT INTO roles (id,name) VALUES (2,'ROLE_MODERATOR');
INSERT INTO roles (id,name) VALUES (1,'ROLE_USER');
-- INSERT INTO drinks_tbl (id, name, price, quantity) VALUES (4,'Black Coffee',4,1);
-- INSERT INTO drinks_tbl (id, name, price, quantity) VALUES (5,'Latte',5,1);
-- INSERT INTO drinks_tbl (id, name, price, quantity) VALUES (6,'Mocha',6,1);
-- INSERT INTO drinks_tbl (id, name, price, quantity) VALUES (7,'Tea',3,1);
-- INSERT INTO toppings_tbl (id, name, orders, price, quantity) values (8,'Milk',0,2,1);
-- INSERT INTO toppings_tbl (id, name, orders, price, quantity) values (9,'Hazelnut syrup',0,3,1);
-- INSERT INTO toppings_tbl (id, name, orders, price, quantity) values (10,'Chocolate sauce',0,5,1);
-- INSERT INTO toppings_tbl (id, name, orders, price, quantity) values (11,'Lemon',0,2,1);